#!/usr/bin/env bash
# $HeadURL::                                                                                      $
# $Id$
#
# Tomcat init script
# Copyright (c) 2006 by Topaz, Inc.
# http://topazproject.org
#
# Licensed under the Educational Community License version 1.0
# http://opensource.org/licenses/ecl1.php

# What to customize/do:
# - Define defaults and/or overrides (minimum is <basename>_CATALINA_HOME)
# - Ensure the jsvc binary is somewhere

# Notes:
#  jsvc pretty much insists on being root
#  jsvc must be in PATH (build it from $CATALINA_HOME/bin/jsvc.tar.gz)
#    Recommend /usr/local/bin (and add this to root's path)
#  We will run as USER
#    (unless variable is undefined -- remove it AND undefine it before running)
#  Tested with jakarta-tomcat-5.0.28 & 5.5

# Defaults:
CATALINA_HOME=
USER="topaz"
JAVA_HOME="/usr/local/topaz/java"
TOMCAT_OPTS="-Xmx256m"
VARDIR="/var"
LOGDIR="${VARDIR}/log/tomcat"
PIDDIR="${VARDIR}/run/tomcat"
JSVC="jsvc"
JVM="server"

# Overrides: basename_CATALINA_HOME, basename_TOMCAT_OPTS, basename_USER
SERVERS="ecqs mckoi mulgara fedora search topaz plosone"
ecqs_CATALINA_HOME=/usr/local/topaz/esup-cas-quick-start-2.0.6-1/jakarta-tomcat-5.0.28
ecqs_TOMCAT_OPTS="-Xmx256m"
topaz_CATALINA_HOME=/usr/local/topaz/topaz-tomcat55
search_CATALINA_HOME=/usr/local/topaz/search-tomcat55
mulgara_CATALINA_HOME=/usr/local/topaz/mulgara-tomcat55
plosone_CATALINA_HOME=/usr/local/topaz/plosone-tomcat55

# These ports are only for printing status. If they're accurate, status will be better
PORT=
ecqs_PORT=7443
topaz_PORT=8000
search_PORT=9092
mulgara_PORT=9091
plosone_PORT=8080
fedora_PORT=9090
mckoi_PORT=9157

#
# Should not need to modify stuff below here
#

# Optionally change basename (used mostly for testing)
if [ "--basename" == "$1" -o "-b" == "$1" ]; then
  BASENAME=$2
  shift 2
else
  BASENAME=$(basename $0)
fi

# Define log and pid files
STDLOG="${LOGDIR}/${BASENAME}.log"
ERRLOG="${LOGDIR}/${BASENAME}.err"
PIDFILE="${PIDDIR}/${BASENAME}-jsvc.pid"

# Log stuff w/date as tomcat doesn't include dates when logging!
log() { echo "`date` $*" | tee -a $STDLOG >> $ERRLOG; echo $*; }

# Expand configuration (use appropriate overrides or defaults if no overrides)
expand () { eval "$1=\${${BASENAME}_$1:-\$$1}"; }
expand CATALINA_HOME
expand TOMCAT_OPTS
expand USER
expand PORT

# Having CATALINA_HOME set properly is critical
check_catalina() {
  [ -z "$CATALINA_HOME" ] && log "Must set/define CATALINA_HOME (for $BASENAME)" && exit 1
  [ \! -d "$CATALINA_HOME" ] && log "CATALINA_HOME ($CATALINA_HOME) does not exist" && exit 1
}

# Setup other catalina defaults
CATALINA_ENDORSED_DIRS=${CATALINA_HOME}/common/endorsed
CATALINA_POLICY=${CATALINA_HOME}/conf/catalina.policy

# Compute classpath
getjars () { echo `(cd /; find $1 -name '*.jar')` | tr ' ' ':'; }
TC=${CATALINA_HOME}
CLASSPATH="$TC/bin/bootstrap.jar:$TC/bin/commons-logging-api.jar"
# Add /etc/topaz/container/<basename>/lib/*.jar OR /etc/topaz/container/common/lib/*.jar
if [ -d /etc/topaz/container/$BASENAME/lib ]; then
  EXTRA_CLASSES=`getjars /etc/topaz/container/$BASENAME/lib`
elif [ -d /etc/topaz/container/common/lib ]; then
  EXTRA_CLASSES=`getjars /etc/topaz/container/common/lib`
fi
[ -n "$EXTRA_CLASSES" ] && CLASSPATH=$EXTRA_CLASSES:$CLASSPATH
# Add /etc/topaz/container/<basename>/classes OR /etc/topaz/container/common/classes
CLASS_OVERRIDES=common
[ -d /etc/topaz/container/$BASENAME/classes ] && CLASS_OVERRIDES=$BASENAME
CLASSPATH=/etc/topaz/container/$CLASS_OVERRIDES/classes:$CLASSPATH
# Add the javac compiler
CLASSPATH="$JAVA_HOME/lib/tools.jar:$CLASSPATH"

# Define options for JSVC
JSVC_OPTS="-outfile ${STDLOG} -errfile ${ERRLOG} -pidfile ${PIDFILE} -cp ${CLASSPATH}"
[ -n "$JVM" ] && JSVC_OPTS="${JSVC_OPTS} -jvm ${JVM}"
[ -n "$USER" ] && JSVC_OPTS="$JSVC_OPTS -user ${USER}"
JSVC_OPTS="${JSVC_OPTS} \
  -Djava.endorsed.dirs=${CATALINA_ENDORSED_DIRS} \
  -Dcatalina.base=${CATALINA_HOME} \
  -Dcatalina.home=${CATALINA_HOME}"
#  -Djava.security.manager \
#  -Djava.security.policy=${CATALINA_POLICY}
JSVC_OPTS="${JSVC_OPTS} ${TOMCAT_OPTS}"

# Find jsvc (in case root's PATH) doesn't contain it
if which ${JSVC} >/dev/null 2>&1; then
  # For some reason, jsvc has trouble starting if it is not an absolute path
  JSVC=`which ${JSVC}`
elif [ -x "${TC}/bin/jsvc" ];          then JSVC="${TC}/bin/jsvc"
elif [ -x /usr/local/topaz/bin/jsvc ]; then JSVC=/usr/local/topaz/bin/jsvc
elif [ -x /usr/local/bin/jsvc ];       then JSVC=/usr/local/bin/jsvc
fi

# Find lsof (in case root's PATH doesn't contain it)
LSOF=`which lsof`
[ -z "$LSOF" ] && LSOF=/usr/sbin/lsof

# You must be root to run jsvc
test_root() { [ `id -u` -ne 0 ] && echo "You must be root!" && exit 1; }

# Create dirs
create_dirs() { mkdir -p ${LOGDIR} ${PIDDIR}; }

jsvc() {
  check_catalina
  # Make sure that we have jsvc
  if ! which ${JSVC} >/dev/null 2>&1; then
    echo "Cannot find ${JSVC} executable"
    echo "Install from ${CATALINA_HOME}/bin/jsvc.tar.gz"
    exit 1
  fi
  # It seems important to start from CATALINA_HOME to read server.xml
  cd ${CATALINA_HOME}
  ${JSVC} ${JSVC_OPTS} $* org.apache.catalina.startup.Bootstrap
}

jsvc_start() {
  # Create dirs if they don't exist
  mkdir -p ${LOGDIR}
  mkdir -p ${PIDDIR}
  [ -n "$USER" ] && chown -R ${USER} ${LOGDIR}

  # Start and wait a while for it to start properly
  jsvc -wait 10
  chmod ugo+r ${PIDFILE}
}


case "$1" in
  start)
    # Don't try to start up twice!
    if [ -e ${PIDFILE} ]; then
      PID=`cat ${PIDFILE}`
      if ps -p ${PID} >/dev/null; then
        echo "${BASENAME} already running (${PID})"
	exit 0
      fi
    fi
    # jsvc doesn't abort if somebody else is on our port, so let's be smart!
    if [ -n "$PORT" ]; then
      TMPFILE=/tmp/${BASENAME}.status.$$
      if $LSOF -i:$PORT -Fp > ${TMPFILE}; then
        echo "No PID file for ${BASENAME}, but port $PORT already in use by pid `cat ${TMPFILE}`"
	rm -f ${TMPFILE}
	exit 1
      fi
    fi
    test_root
    create_dirs
    log "Starting ${BASENAME} in ${CATALINA_HOME}"
    jsvc_start
    ;;
  stop)
    test_root
    create_dirs
    PID=`cat ${PIDFILE} 2>/dev/null`
    log "Stopping ${BASENAME} (${PID})"
    jsvc -stop
    if [ -e ${PIDFILE} ]; then
      echo "Unable to stop ${BASENAME} (${PID})"
      kill -QUIT ${PID}
      exit 1
    fi
    ;;
  restart|reload)
    test_root
    create_dirs
    PID=`cat ${PIDFILE} 2>/dev/null`
    log "Restarting ${BASENAME} (${PID}) in ${CATALINA_HOME}"
    jsvc -stop
    jsvc_start
    ;;
  status|check)
    if [ -e ${PIDFILE} ]; then
      PID=`cat ${PIDFILE}`
      TMPFILE=/tmp/${BASENAME}.status.$$
      if ps o "pid user rss %mem etime time %cpu comm" -p ${PID} > ${TMPFILE} 2>&1; then
        echo "${BASENAME} (${PID}) is running from ${CATALINA_HOME}"
        cat ${TMPFILE}
        $LSOF -n -P -i -a -p $PID | grep "LISTEN"
      else
        echo "${BASENAME} not running"
      fi
      rm -f ${TMPFILE}
    else
      echo "${BASENAME} not running"
    fi
    ;;
  report)
    # Spit out a very simple status dump (really used by reportall below)
    # Note: fedora and mckoi will almost always report xxx(unknown)
    if [ -e ${PIDFILE} ]; then
      PID=`cat ${PIDFILE}`
      if ps -p $PID >/dev/null; then
        PORTS=`$LSOF -p $PID -a -iTCP -Fn -n -P | grep -v '-' | sort | uniq | tr 'n' ' '`
        echo "$PID $BASENAME `echo $PORTS`"
      else
        echo "$BASENAME not running -- but PIDFILE ($PIDFILE:$PID) exists"
      fi
    elif [ -n "$PORT" ]; then
      PID=`$LSOF -i:$PORT | grep LISTEN | awk '{print $2}'`
      if [ -n "$PID" ]; then
        PORTS=`$LSOF -p $PID -a -iTCP -Fn -n -P | grep -v '-' | sort | uniq | tr 'n' ' '`
        echo "`echo $PID` unknown($BASENAME) `echo $PORTS`"
      else
        # No PIDFILE and noting listening on our configured PORT
        echo "$BASENAME not running on port $PORT"
      fi
    else
      # No PIDFILE and no configured PORT
      echo "$BASENAME not running"
    fi
    ;;
  reportall)
    for server in ${SERVERS}; do
      $0 --basename $server report
    done
    ;;
  *)
    echo "Usage: $0 [--basename name] {start|stop|restart|status}"
    exit 1
esac

exit $?
