#!/bin/bash

# chkconfig: 345 93 13
# description: topaz fedora server

# Get name of thing we're trying to control
BASENAME=$(basename `readlink -f $0`)
USER=topaz

# Set these if we haven't overriden them in the environment
[ -z "$MVN" ] && MVN=/usr/local/topaz/maven/bin/mvn
[ -z "$BASEDIR" ] && BASEDIR=/etc/topaz/${BASENAME}

JAVA_HOME=/usr/local/topaz/java
INSTALL_DIR=/usr/local/topaz

STARTGOAL="ant-tasks:${BASENAME}-start"
STOPGOAL="ant-tasks:${BASENAME}-stop"
MVNARGS="--offline --batch-mode -Dtopazproject.install.dir=$INSTALL_DIR"

# Change to the directory where a copy of the ant-tasks pom.xml is
cd ${BASEDIR}

start() {
    su - ${USER} -c "JAVA_HOME=$JAVA_HOME ${MVN} -DSPAWN=true ${MVNARGS} ${STARTGOAL}"
}

stop() {
    su - ${USER} -c "JAVA_HOME=$JAVA_HOME ${MVN} ${MVNARGS} ${STOPGOAL}"
}

restart() {
    stop
    start
}


case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
