#!/bin/bash

# chkconfig: 345 93 13
# description: topaz fedora server

# Get name of thing we're trying to control
BASENAME=$(basename $0)
USER=topaz

# Set these if we haven't overriden them in the environment
[ -z "$MVN" ] && MVN=/usr/local/topaz/maven/bin/mvn
[ -z "$BASEDIR" ] && BASEDIR=/etc/topaz/${BASENAME}

STARTGOAL="ant-tasks:${BASENAME}-start"
STOPGOAL="ant-tasks:${BASENAME}-stop"
MVNARGS="-X -e --offline --batch-mode"

# Change to the directory where a copy of the ant-tasks pom.xml is
cd ${BASEDIR}

start() {
    echo su ${USER} -c "${MVN} -DSPAWN=true ${MVNARGS} ${STARTGOAL}"
    su ${USER} -c "${MVN} -DSPAWN=true ${MVNARGS} ${STARTGOAL}"
}

stop() {
    su ${USER} -c "${MVN} ${MVNARGS} ${STOPGOAL}"
}

restart() {
    stop
    start
}


case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
