#!/usr/bin/env bash
# $HeadURL:: http://gandalf/svn/head/deploy/etc/init.d/mulgara                                    $
# $Id: mulgara 1343 2006-11-26 06:49:27Z ebrown $
#
# Tomcat init script
# Copyright (c) 2006 by Topaz, Inc.
# http://topazproject.org
#
# Licensed under the Educational Community License version 1.0
# http://opensource.org/licenses/ecl1.php

# chkconfig: 345 92 14
# description: mulgara rdf database

# What to customize/do:
# - chkconfig and description lines above
# - Read and update configuration in /usr/local/topaz/bin/tomcat
#   (Check any changes back into svn -- head/deploy/src

ifconfig eth0 multicast
ifconfig lo multicast
route add -net 224.0.0.0 netmask 240.0.0.0 dev eth0
route add -net 224.0.0.0 netmask 240.0.0.0 dev lo

