#!/usr/bin/env bash
# $HeadURL::                                                                                      $
# $Id$
#
# Tomcat init script
# Copyright (c) 2006 by Topaz, Inc.
# http://topazproject.org
#
# Licensed under the Educational Community License version 1.0
# http://opensource.org/licenses/ecl1.php

# chkconfig: 345 96 10
# description: plosone container

# What to customize/do:
# - chkconfig and description lines above
# - Read and update configuration in /usr/local/topaz/bin/tomcat
#   (Check any changes back into svn -- head/deploy/src

/usr/local/topaz/bin/tomcat --basename $(basename `readlink -f $0`) $*
