	dojo.registerModulePath("topaz", "../topaz");
	dojo.registerModulePath("topaz.dojoCustom.widget", "../topaz/dojoCustom/widget");
	dojo.require("topaz.topaz");
	dojo.require("dojo.widget.Dialog");
//	dojo.registerModulePath("dojo.dojo_custom", "dojo_custom.js");
	dojo.require("dojo.widget.RegionalDialog");
	dojo.require("topaz.dojoCustom.widget.ProgressCycle");
  dojo.require("dojo.io.*");
  dojo.require("dojo.event.*");
  dojo.require("dojo.json");
