	slideshow[0] = {imageUri: 'http://biology.plosjournals.org/archive/1545-7885/4/12/figure/10.1371_journal.pbio.0040409.g001', 
	                title: 'Figure 1. Fluorescent Labeling of DGCs Born during Early Postnatal and Adult Neurogenesis',
	                titlePlain: 'Figure 1. Fluorescent Labeling of DGCs Born during Early Postnatal and Adult Neurogenesis',
	                description: '<p class="figureLegend"><p>(A) and (B) Retroviral delivery of GFP into DGCs generated at P7 (A) and P42 (B), analyzed 7 wk after each injection. The GCL was labeled by immunohistochemistry for the neuronal marker NeuN (blue). Images are merges of 27 (A) and 21 (B) confocal planes taken from coronal sections (40-&mu;m thick). H, hilus; ML, molecular layer.</p><p>(C) and (D) Double retroviral labeling of DGCs generated at P7 (GFP<sup>&#043;</sup>, green) and P42 (RFP<sup>&#043;</sup>, red). Images are merges of nine (C) and 20 (D) confocal planes taken from fixed transverse sections of the DG (400-&mu;m thick) from 13-wk-old mice.</p><p>(E) Double labeling of DGCs with GFP (green) and BrdU (red): intrahippocampal injections of CAG-GFP retrovirus in P7 were followed by daily injections of BrdU carried out from P21 to P25; brains were analyzed at P53. The image is a merge of 16 confocal planes.</p><p>(F) Example of a sporadic event of co-localization of GFP, BrdU, and NeuN shown by a single optical section for the green, red, and blue channels. Their overlay is shown together with the orthogonal projections onto the <em>x-z</em> (top) and <em>y-z</em> (right) planes.</p><p>(G) Number of GFP<sup>&#043;</sup> or BrdU<sup>&#043;</sup> cells per mouse (left) and the percentage of GFP<sup>&#043;</sup> cells showing BrdU label (right). Data are mean &plusmn; standard error of the mean (SEM) (<em>n</em> &#061; 3 mice). Scale bars indicate 50 &mu;m (A&#8211;E) or 10 &mu;m (F).</p>			</p><p class="notes">From: <span><a href="http://biology.plosjournals.org/perlserv/?request=get-document&#38;doi=10.1371/journal.pbio.0040409"  >Functional Convergence of Neurons Generated in the Developing and Adult Hippocampus</a></span> Laplagne DA,&nbsp;Esp&oacute;sito MS,&nbsp;Piatti VC,&nbsp;Morgenstern NA,&nbsp;Zhao C, et al.		<span class="citation"><i>PLoS Biology</i> Vol. 4, No. 12, e409 doi:10.1371/journal.pbio.0040409</span>'};
	
	slideshow[1] = {imageUri: 'http://biology.plosjournals.org/archive/1545-7885/4/12/figure/10.1371_journal.pbio.0040409.g002', 
	                title: 'Figure 2. Entorhinal Glutamatergic Afferents onto Mature Neurons Generated in the Developing and Adult Hippocampus',
	                titlePlain: 'Figure 2. Entorhinal Glutamatergic Afferents onto Mature Neurons Generated in the Developing and Adult Hippocampus',
	                description: '<p class="figureLegend"><p>(A) Schematic diagram of experimental design for retroviral labeling and electrophysiological recordings.</p><p>(B) A paired experiment. Upper row: a RFP<sup>&#043;</sup> neuron was patched (cell &#8220;1&#8221;) and filled with Alexa Fluor 488 (green). Lower row: a neighboring GFP<sup>&#043;</sup> neuron (cell &#8220;2&#8221;) was subsequently patched and filled with Alexa Fluor 594 (red). Both DGCs are in the same field, although at different focal planes (see merge channel). At the end of the experiment, both cells display green and red fluorescence (merge). Scale bar indicates 10 &mu;m.</p><p>(C) Schematic diagram of the DG showing the position of the bipolar electrodes for the stimulation of the MPP and LPP.</p><p>(D) Example of EPSCs from an adult-born DGC at V<sub>hold</sub> &#061; &#043;50 mV (top) and &minus;80 mV (bottom) elicited by LPP stimulation recorded in the presence of vehicle (&#8220;control&#8221;) or 20 &mu;M DNQX &#043; 100 &mu;M AP-5. Scale bars indicate 20 ms, 40 pA (top) or 20 pA (bottom). Similar properties were observed in DGCs born during development (unpublished data)</p><p>(E) Example of a paired experiment. Sequential recordings of two neighboring pup and adult DGCs in response to paired-pulse stimulation (100-Ss interval) of the MPP and LPP. Scale bars represent 25 ms, 50 pA.</p><p>(F) Paired-pulse ratio (left) and 20&#037;&#8211;80&#037; rise time (right) of EPSCs recorded from pup and adult DGCs upon stimulation of MPP and LPP (<em>n</em> &#061; 11 to 15) Paired-pulse ratio was measured as the ratio between the amplitude of the second pulse over the first. Two-way analysis of variance (ANOVA) revealed a significant effect of MPP versus LPP for paired-pulse ratio (<em>p</em> &#061; 0.0002) and rise time (<em>p</em> &#061; 0.0017), but no significant effect of pup versus adult (Adu) for either parameter.</p><p>(G) Peak EPSC amplitude recorded in paired experiments from DGCs born during development (Pup) and adulthood (Adult) upon stimulation of the MPP (<em>n</em> &#061; 15 pairs, <em>p</em> &#061; 0.3, paired <em>t</em>-test) or LPP (<em>n</em> &#061; 11 pairs, <em>p</em> &#061; 0.049). Mean &plusmn; SEM is shown on the sides. Recordings were carried out in the presence of 20 &mu;M BMI in slices obtained from mice aged 19&#8211;21 wk. Neurons were approximately 18 wk old (P7) and approximately 13 wk old (P42). All plots depict mean &plusmn; SEM.</p>			</p><p class="notes">From: <span><a href="http://biology.plosjournals.org/perlserv/?request=get-document&#38;doi=10.1371/journal.pbio.0040409"  >Functional Convergence of Neurons Generated in the Developing and Adult Hippocampus</a></span> Laplagne DA,&nbsp;Esp&oacute;sito MS,&nbsp;Piatti VC,&nbsp;Morgenstern NA,&nbsp;Zhao C, et al.		<span class="citation"><i>PLoS Biology</i> Vol. 4, No. 12, e409 doi:10.1371/journal.pbio.0040409</span>'};
	
	slideshow[2] = {imageUri: 'http://biology.plosjournals.org/archive/1545-7885/4/12/figure/10.1371_journal.pbio.0040409.g003', 
	                title: 'Figure 3. Short-Term Plasticity of Entorhinal Glutamatergic Afferents',
	                titlePlain: 'Figure 3. Short-Term Plasticity of Entorhinal Glutamatergic Afferents',
	                description: '<p>(A) Average EPSCs recorded at V<sub>Hold</sub> &#061; &minus;80 mV (downward deflections) and &#043;50 mV (upward deflections) from pup and adult DGCs (<em>n</em> &#061; 8 to 11) upon stimulation of MPP or LPP. Dashed line indicates zero level. Arrowheads denote time points for quantification of AMPA (open triangles) and NMDA (filled triangles) currents shown in (B). Criteria for AMPA/NMDA quantification are detailed in the Materials and Methods section. Scale bars indicate 20 ms, 100 pA.</p><p>(B) AMPA/NMDA ratio from pup and adult DGCs (<em>n</em> &#061; 9 to 13) in response to MPP or LPP stimulation. Two-way ANOVA revealed a significant effect of MPP versus LPP (<em>p</em> &#061; 0.006), but no significant effect of pup versus adult (<em>p</em> &#061; 0.63).</p><p>(C) Averages of EPSCs in response to paired-pulse stimulation of the MPP or LPP delivered at increasing interpulse intervals (20, 50, 100, and 500 ms). Traces are averages of 7&#8211;14 cells aligned and normalized to the first EPSC. Stimulation artifacts and late decay phases of the second EPSC were removed for clarity. Scale bar indicates 100 ms.</p><p>(D) Paired-pulse ratio as a function of interpulse interval for the experiments shown in (C). Two-way ANOVAs revealed a significant effect of interpulse interval for MPP (dashed lines, <em>p</em> &lt; 0.0001) and LPP (solid lines, <em>p</em> &lt; 0.0001), but no significant effect of pup (green lines, solid circles) versus adult (red lines, open circles) for either MPP (<em>p</em> &#061; 0.073) or LPP (<em>p</em> &#061; 0.72) stimulation (<em>n</em> &#061; 9 to 14)</p><p>(E) Example of EPSCs from a pup (green) and an adult DGC (red) in response to MPP stimulation (ten pulses, 50 Hz) Traces are normalized to the first EPSC amplitude. Scale bar indicates 40 ms.</p><p>(F) Relative EPSC amplitudes measured in response to 50-Hz stimulation evoked as shown in (E). No difference was found between pup and adult responses (two-way ANOVA, <em>p</em> &#061; 0.49, <em>n</em> &#061; 10 pups &#091;solid circles&#093;, <em>n</em> &#061; 4 adults &#091;open circles&#093;). All recordings were carried out in the presence of 20-&mu;m BMI. Neurons were approximately 18 wk old (pup) and approximately 13 wk old (adult). All plots depict mean &plusmn; SEM.</p></p><p class="notes">From: <span><a href="http://biology.plosjournals.org/perlserv/?request=get-document&#38;doi=10.1371/journal.pbio.0040409"  >Functional Convergence of Neurons Generated in the Developing and Adult Hippocampus</a></span> Laplagne DA,&nbsp;Esp&oacute;sito MS,&nbsp;Piatti VC,&nbsp;Morgenstern NA,&nbsp;Zhao C, et al.		<span class="citation"><i>PLoS Biology</i> Vol. 4, No. 12, e409 doi:10.1371/journal.pbio.0040409</span>'};
	
	slideshow[3] = {imageUri: 'http://biology.plosjournals.org/archive/1545-7885/4/12/figure/10.1371_journal.pbio.0040409.g004', 
	                title: 'Figure 4. GABAergic Inputs Elicited by GCL Stimulation',
	                titlePlain: 'Figure 4. GABAergic Inputs Elicited by GCL Stimulation',
	                description: '<p>(A) Example of evoked IPSCs recorded from a pup-born DGC in response to extracellular stimulation of the GCL before (control), during (BMI), and after (wash) application of 20 &mu;M BMI. Scale bars indicate 25 ms, 20 pA. Inset: schematic diagram of the DG showing the position of the bipolar electrode for the stimulation of GCL interneurons. Experiments were carried out with internal solution containing low &#091;Cl<sup>&minus;</sup>&#093;.</p><p>(B) Typical traces of IPSCs evoked on a pup (green) and adult (red) DGC recorded from the same slice in a paired experiment. Scales indicate 25 ms, 40 pA.</p><p>(C) Paired analysis of peak IPSC amplitude recorded from a pup versus adult DGCs (<em>n</em> &#061; 19 pairs, <em>p</em> &#061; 0.97, paired <em>t</em>-test). Mean &plusmn; SEM are shown on the sides.</p><p>(D) Kinetics of evoked IPSCs (<em>n</em> &#061; 40 adults, <em>n</em> &#061; 22 pups; rise time, <em>p</em> &#061; 0.31; decay time, <em>p</em> &#061; 0.19; unpaired <em>t</em>-tests). Inset: scaled average traces of evoked IPSCs. Scale bar indicates 50 ms.</p><p>(E) and (F) Examples of I-V curves of evoked IPSCs recorded from pup (E) and adult DGCs (F). Top: sample traces of IPSCs recorded at the holding potentials shown on the right (mV). Scale bars indicate 50 ms, 100 pA (E) and 50 pA (F). Bottom: I-V plots measured at time points indicated with arrowheads (early: filled triangles/dashed lines, late: open triangles/solid lines).</p><p>(G) E<sub>GABA</sub> measured at early and late time points. Two-way ANOVA (<em>n</em> &#061; 11, pup; <em>n</em> &#061; 16, adult) revealed a significant effect of early versus late points (<em>p</em> &lt; 0.0001), but not of pup versus adult (Adu) neurons (<em>p</em> &#061; 0.56).</p><p>(H) Conductance profile of IPSCs. Each value denotes the slope conductance measured from the I-V curve at the time points indicated on the sample traces (inset). No significant differences were found between pup (green) and adult (red; 11 <img border="0" src="/charent/iso_characters_mixed/lowercase/le.gif"/> n <img border="0" src="/charent/iso_characters_mixed/lowercase/le.gif"/> 16, <em>p</em> &#061; 0.62, two-way ANOVA). Scale indicates 50 ms. All experiments were conducted in the presence of kyn (4 mM) in slices obtained from mice aged 13&#8211;14 wk. Neurons were approximately 12 wk old (P7) and approximately 7 wk old (P42).</p></p><p class="notes">From: <span><a href="http://biology.plosjournals.org/perlserv/?request=get-document&#38;doi=10.1371/journal.pbio.0040409"  >Functional Convergence of Neurons Generated in the Developing and Adult Hippocampus</a></span> Laplagne DA,&nbsp;Esp&oacute;sito MS,&nbsp;Piatti VC,&nbsp;Morgenstern NA,&nbsp;Zhao C, et al.		<span class="citation"><i>PLoS Biology</i> Vol. 4, No. 12, e409 doi:10.1371/journal.pbio.0040409</span>'};
	
	slideshow[4] = {imageUri: 'http://biology.plosjournals.org/archive/1545-7885/4/12/figure/10.1371_journal.pbio.0040409.g005', 
	                title: 'Figure 5. GABAergic Inputs Evoked by ML Stimulation',
	                titlePlain: 'Figure 5. GABAergic Inputs Evoked by ML Stimulation',
	                description: '<p>(A) Example of evoked IPSCs recorded from a pup-born DGC in response to extracellular stimulation of the ML before (control), during (BMI), and after (wash) application of 20 &mu;M BMI. Scale bars indicate 25 ms, 20 pA. Inset: schematic diagram of the DG showing the position of the bipolar electrode for the stimulation of ML interneurons. Experiments were carried out with internal solution containing low &#091;Cl<sup>&minus;</sup>&#093;.</p><p>(B) Kinetics of IPSCs evoked on pup versus adult DGCs (pup, <em>n</em> &#061; 6; adult, <em>n</em> &#061; 14; rise time, <em>p</em> &#061; 0.85; decay time, <em>p</em> &#061; 0.90, paired <em>t</em>-tests). Inset: scaled averages of IPSCs (pup, green; adult, red). Scale bar indicates 50 ms.</p><p>(C) and (D) Examples of I-V curves of evoked IPSCs recorded from pup (C) or adult (D) DGCs. Top: sample traces of IPSCs recorded at the holding potentials shown on the right (mV). Scale bar indicates 50 ms, 10 pA. Bottom: I-V plots measured at the time indicated by the arrowheads.</p><p>(E) E<sub>GABA</sub> of IPSCs (pup, <em>n</em> &#061; 7; adult, <em>n</em> &#061; 11; <em>p</em> &#061; 0.67, <em>t</em>-test).</p><p>(F) Slope conductance measured at the IPSC peak (<em>n,</em> same as in &#091;E&#093;; <em>p</em> &#061; 0.23; <em>t</em>-test). All experiments conducted in the presence of kyn (4 mM) in neurons aged 12 wk (P7) and 7 wk (P42).</p></p><p class="notes">From: <span><a href="http://biology.plosjournals.org/perlserv/?request=get-document&#38;doi=10.1371/journal.pbio.0040409"  >Functional Convergence of Neurons Generated in the Developing and Adult Hippocampus</a></span> Laplagne DA,&nbsp;Esp&oacute;sito MS,&nbsp;Piatti VC,&nbsp;Morgenstern NA,&nbsp;Zhao C, et al.		<span class="citation"><i>PLoS Biology</i> Vol. 4, No. 12, e409 doi:10.1371/journal.pbio.0040409</span>'};
	
	slideshow[5] = {imageUri: 'http://biology.plosjournals.org/archive/1545-7885/4/12/figure/10.1371_journal.pbio.0040409.g006', 
	                title: 'Figure 6. Fast-Perisomatic sIPSCs',
	                titlePlain: 'Figure 6. Fast-Perisomatic sIPSCs',
	                description: '<p>(A) and (B) Example of traces of inward sIPSCs recorded from a pup (A) and adult (B) DGC. Dashed box on each top trace denotes expanded segment on the bottom. Scale bars indicate 1 s/50 ms (top/bottom), 40 pA.</p><p>(C) and (D) Two-dimensional histograms of rise and decay time of individual sIPSCs recorded from pup (&#091;C&#093; <em>n</em> &#061; 5,871 events) and adult DGCs (&#091;D&#093; <em>n</em> &#061; 8,183 events). Color scale indicates the relative frequency for each bin (square areas in the graph).</p><p>(E) Cumulative histograms of rise and decay time of all sIPSCs recorded from pup (green) and adult (red) DGCs. Data are the same as shown in (C) and (D).</p><p>(F) Frequency of sIPSCs (pup, <em>n</em> &#061; 12 neurons; adult, <em>n</em> &#061; 15; <em>p</em> &#061; 0.99; <em>t</em>-test).</p><p>(G) Peak amplitude of sIPSCs (<em>n</em>, same as in &#091;F&#093;; <em>p</em> &#061; 0.44).</p><p>(H) Kinetics of sIPSCs. Inset: scaled averages of sIPSCs (pup, green; adult, red). Scale bar indicates 10 ms. All experiments conducted in the presence of kyn at V<sub>hold</sub> &#061; &minus;80 mV with an internal solution containing high &#091;Cl<sup>&minus;</sup>&#093;. (<em>n</em>, same as in &#091;F&#093;; rise time, <em>p</em> &#061; 0.96; decay time, <em>p</em> &#061; 0.72).</p></p><p class="notes">From: <span><a href="http://biology.plosjournals.org/perlserv/?request=get-document&#38;doi=10.1371/journal.pbio.0040409"  >Functional Convergence of Neurons Generated in the Developing and Adult Hippocampus</a></span> Laplagne DA,&nbsp;Esp&oacute;sito MS,&nbsp;Piatti VC,&nbsp;Morgenstern NA,&nbsp;Zhao C, et al.		<span class="citation"><i>PLoS Biology</i> Vol. 4, No. 12, e409 doi:10.1371/journal.pbio.0040409</span>'};
	
	slideshow[6] = {imageUri: 'http://biology.plosjournals.org/archive/1545-7885/4/12/figure/10.1371_journal.pbio.0040409.g007', 
	                title: 'Figure 7. Slow-Dendritic sIPSCs',
	                titlePlain: 'Figure 7. Slow-Dendritic sIPSCs',
	                description: '<p>(A) and (B) Example of traces of outward sIPSCs recorded from a pup (A) and adult (B) DGC. Dashed box on each top trace denotes expanded segment on the bottom. Scales indicate 0.5 s/50 ms (top/bottom), 10 pA.</p><p>(C) and (D) Two-dimensional histograms of rise and decay time of individual sIPSCs recorded from pup (&#091;C&#093; <em>n</em> &#061; 695 events) and adult DGCs (&#091;D&#093; <em>n</em> &#061; 1,160 events). Color scale indicates the relative frequency for each bin.</p><p>(E) Cumulative histograms of rise and decay time of all sIPSCs recorded from pup (green) and adult DGCs (red). Same data as shown in (C) and (D).</p><p>(F) Frequency of sIPSCs (pup, <em>n</em> &#061; 10 neurons; adult, <em>n</em> &#061; 16; <em>p</em> &#061; 0.94; <em>t</em>-test).</p><p>(G) Peak amplitude of sIPSCs (pup, <em>n</em> &#061; 10; adult, <em>n</em> &#061; 14; <em>p</em> &#061; 0.44).</p><p>(H) Kinetics of sIPSCs. Inset: scaled averages of sIPSCs (pup, green; adult, red). Scale bar indicates 50 ms. All experiments conducted in the presence of kyn at V<sub>hold</sub> &#061; 0 mV with an internal solution containing high &#091;Cl<sup>&minus;</sup>&#093;. (<em>n</em>, same as in &#091;F&#093;; rise time, <em>p</em> &#061; 0.37; decay time, <em>p</em> &#061; 0.41).</p></p><p class="notes">From: <span><a href="http://biology.plosjournals.org/perlserv/?request=get-document&#38;doi=10.1371/journal.pbio.0040409"  >Functional Convergence of Neurons Generated in the Developing and Adult Hippocampus</a></span> Laplagne DA,&nbsp;Esp&oacute;sito MS,&nbsp;Piatti VC,&nbsp;Morgenstern NA,&nbsp;Zhao C, et al.		<span class="citation"><i>PLoS Biology</i> Vol. 4, No. 12, e409 doi:10.1371/journal.pbio.0040409</span>'};
	
	slideshow[7] = {imageUri: 'http://biology.plosjournals.org/archive/1545-7885/4/12/figure/10.1371_journal.pbio.0040409.g008', 
	                title: 'Figure 8. Firing Behavior Elicited by Excitatory Inputs',
	                titlePlain: 'Figure 8. Firing Behavior Elicited by Excitatory Inputs',
	                description: '<p>(A) Action currents in cell-attached configuration recorded from an adult-born DGC in response to MPP stimulation at increasing stimulus strengths (0.5&#8211;1.5 mA, 50 &mu;s). Six representative epochs are shown. Spiking probability (p) is shown below the traces. The asterisk (&#042;) marks the stimulation artifact. Scale indicates 10 ms, 50 pA.</p><p>(B) Sample experiment of simultaneous cell-attached recordings of DGCs born in pup and adult brain in response to MPP stimulation (0.4 mA, 50 &mu;s). Action currents indicate a higher spiking probability in the pup DGC. Scales indicate 10 ms, 50 pA (left) and 20 pA (right).</p><p>(C) Sample experiment in which the spiking probability is higher in the adult-born DGC (1.5 mA, 50 &mu;s). Scale indicates 10 ms, 30 pA.</p><p>(D) Firing behavior of DGCs born in pup and adult brain during simultaneous paired experiments. No significant difference was found (<em>n</em> &#061; 14 pairs, <em>p</em> &#061; 0.8, Wilcoxon signed rank test). All recordings were carried out in the presence of BMI (20 &mu;M). In this set of experiments, adult-born neurons were retrovirally labeled with GFP, whereas unlabeled DGCs of the middle third of the GCL were considered postnatally born (see Materials and Methods). Repetitive (&gt;15 episodes) slow frequency stimulation was used to measure the spiking probability for each neuron at the given stimulus.</p></p><p class="notes">From: <span><a href="http://biology.plosjournals.org/perlserv/?request=get-document&#38;doi=10.1371/journal.pbio.0040409"  >Functional Convergence of Neurons Generated in the Developing and Adult Hippocampus</a></span> Laplagne DA,&nbsp;Esp&oacute;sito MS,&nbsp;Piatti VC,&nbsp;Morgenstern NA,&nbsp;Zhao C, et al.		<span class="citation"><i>PLoS Biology</i> Vol. 4, No. 12, e409 doi:10.1371/journal.pbio.0040409</span>'};
	
	slideshow[8] = {imageUri: 'http://biology.plosjournals.org/archive/1545-7885/4/12/figure/10.1371_journal.pbio.0040382.g001', 
	                 title: 'Figure 9. Laser Scanning Photostimulation Mapping of Thalamocortical Projections',
	                 titlePlain: 'Figure 9. Laser Scanning Photostimulation Mapping of Thalamocortical Projections',
	                 description: '<p>(A) Montage of a thalamocortical slice.</p><p>(B) Layout of the experiment. Excitatory neurons were recorded in the barrel cortex while thalamic neurons were photostimulated by glutamate uncaging. The map pattern (red grid) was centered on the POm/VPM boundary. Dashed lines indicate a barrel-column.</p><p>(C&#8211;E) Examples of synaptic input maps for individual L4 (C), L5B (D), and L5A (E) neurons. The pixel values encode the mean amplitudes of EPSCs measured within 100 ms after the stimulus (see &#091;G&#093;). The dashed lines indicate the borders between POm, VPM, and the ventral posterolateral nucleus (VPL) (see &#091;B&#093;). Letters mark a pair of pixels corresponding to the traces shown in (G).</p><p>(F) Map of standard deviations across trials for an individual cell (same cell as in &#091;E&#093;).</p><p>(G) Examples of individual EPSCs. The responses were evoked by photostimulation at the sites indicated by letters in (C&#8211;E) (two sites per arrow). Arrowheads indicate the timing of the stimulus; dashed lines indicate the averaging window used for analysis.</p><p>(H) Percentage of cortical cells with thalamic input. The percentage was computed for cells that were within a lateral distance of 300 &mu;m of cells that showed thalamic input in the brain slice.</p></p><p class="notes">From: <span><a href="http://biology.plosjournals.org/perlserv/?request=get-document&#38;doi=10.1371/journal.pbio.0040382"  >Interdigitated Paralemniscal and Lemniscal Pathways in the Mouse Barrel Cortex</a></span> Bureau I,&nbsp;von Saint Paul F,&nbsp;Svoboda K<span class="citation"><i>PLoS Biology</i> Vol. 4, No. 12, e382 doi:10.1371/journal.pbio.0040382</span>'};
	
	slideshow[9] = {imageUri: 'http://biology.plosjournals.org/archive/1545-7885/4/12/figure/10.1371_journal.pbio.0040382.g002', 
	                 title: 'Figure 10. Spatial Resolution of LSPS in the Somatosensory Thalamus',
	                 titlePlain: 'Figure 10. Spatial Resolution of LSPS in the Somatosensory Thalamus',
	                 description: '<p>(A) Photostimulation-evoked APs recorded in loose-patch mode in a POm cell (arrowheads indicate the stimulus). The traces correspond to the 12 pixels in the boxed region shown in (B).</p><p>(B) Excitation profile of a single POm cell. The grid was centered on the soma. Pixel values encode the number of APs in a 100-ms window after photostimulation.</p><p>(C) Average excitation profiles (VPM, <em>n &#061;</em> 7; POm, <em>n &#061;</em> 7).</p><p>(D) Excitation as a function of lateral distance from the soma (at 0). Responses elicited in each column of the 8 &times; 8 grid were summed.</p>			href="http://biology.plosjournals.org/perlserv/?request=get-document&#38;doi=10.1371/journal.pbio.0040382"  >Interdigitated Paralemniscal and Lemniscal Pathways in the Mouse Barrel Cortex</a></span>Bureau I,&nbsp;von Saint Paul F,&nbsp;Svoboda K		<span class="citation"><i>PLoS Biology</i> Vol. 4, No. 12, e382 doi:10.1371/journal.pbio.0040382</span>'};
	
	slideshow[10] = {imageUri: 'http://biology.plosjournals.org/archive/1545-7885/4/12/figure/10.1371_journal.pbio.0040382.g003', 
	                 title: 'Figure 11. Laminar Organization of Thalamocortical Projections',
	                 titlePlain: 'Figure 11. Laminar Organization of Thalamocortical Projections',
	                 description: '<p>Overlay of input domains for L4, L5A, L5B, and L6A cells. The contours enclose regions where the inputs exceed 50&#037; of the largest responses (VPM, green; POm, blue). Dashed contours correspond to pyramidal cells with apical dendrites that were cut below L1. Shaded area denotes the range of POm/VPM boundaries for all experiments.</p></p><p class="notes">From: <span><a href="http://biology.plosjournals.org/perlserv/?request=get-document&#38;doi=10.1371/journal.pbio.0040382"  >Interdigitated Paralemniscal and Lemniscal Pathways in the Mouse Barrel Cortex</a></span>Bureau I,&nbsp;von Saint Paul F,&nbsp;Svoboda K<span class="citation"><i>PLoS Biology</i> Vol. 4, No. 12, e382 doi:10.1371/journal.pbio.0040382</span>'};
	
	slideshow[11] = {imageUri: 'http://biology.plosjournals.org/archive/1545-7885/4/12/figure/10.1371_journal.pbio.0040382.g004', 
	                 title: 'Figure 12. Thalamic Input Domains Projecting to Individual Cortical Columns',
	                 titlePlain: 'Figure 12. Thalamic Input Domains Projecting to Individual Cortical Columns',
	                 description: '<p>(A&#8211;D) Schematic of the locations of recorded neurons (left), input maps (middle), and overlaid input domains (right) Circles in the input domains indicate the largest responses from a pair of L4 cells in the same column (A), a pair of L4 cells in neighboring columns (B), a pair of L5A cells in the same column (C) and a pair of L5A cells in neighboring columns (D).</p><p>(E) Distance between the largest input in the synaptic input maps (green, VPM; blue, POm) from pairs recorded in the same column or in neighboring columns. The average (thick line), and the minimum and maximum distances between largest input across cells (rectangle) are shown. Numbers in parenthesis are the number of pairs. The pairs of cells located in the same column were three L4/L4, five L4/L5B, four L4/L6A, two L5B/L6A, one L6A/L6A, and six L5A/L5A. Pairs of cells located in neighboring columns were four L4/L4, one L4/L5B, and six L5A/L5A cells.</p><p>(F) Areas of the input domains in VPM (green) and POm (blue) for pairs of L4/L5B/L6A, and L5A cells located in the same column.</p></p><p class="notes">From: <span><a href="http://biology.plosjournals.org/perlserv/?request=get-document&#38;doi=10.1371/journal.pbio.0040382"  >Interdigitated Paralemniscal and Lemniscal Pathways in the Mouse Barrel Cortex</a></span>Bureau I,&nbsp;von Saint Paul F,&nbsp;Svoboda K	<span class="citation"><i>PLoS Biology</i> Vol. 4, No. 12, e382 doi:10.1371/journal.pbio.0040382</span>'};
	
	slideshow[12] = {imageUri: 'http://biology.plosjournals.org/archive/1545-7885/4/12/figure/10.1371_journal.pbio.0040382.g005', 
	                 title: 'Figure 13. Thalamocortical Topographic Transformations',
	                 titlePlain: 'Figure 13. Thalamocortical Topographic Transformations',
	                 description: '<p>(A) Schematic of the coordinate system. <em>X</em><sub>ID</sub> and <em>Y</em><sub>ID</sub> are the horizontal and vertical coordinates of the input domain, respectively. <em>X</em><sub>Soma</sub> is the horizontal coordinate of the cell position in cortex. <em>X</em><sub>ID</sub> and <em>X</em><sub>Soma</sub> are measured from the VPM/POm boundary (center of the uncaging grid; light red). <em>Y</em><sub>ID</sub> is measured from the bottom of VPM (bottom of the uncaging grid).</p><p>(B) and (C) Positions of the input domains (<em>Y</em><sub>ID</sub> in B<sub>;</sub> <em>X</em><sub>ID</sub> in C) in VPM (green) and POm (blue) as a function of <em>X</em><sub>Soma</sub>. Cells were in L4 (<em>n &#061;</em> 12); L5B (<em>n &#061;</em> 7); L6A (<em>n &#061;</em> 5); and L5A (<em>n &#061;</em> 21). Dashed line shows the linear correlation between <em>X</em><sub>Soma</sub> and <em>Y</em><sub>ID</sub> for VPM and POm domains (<em>r<sup>2</sup></em> &#061; 0.72).</p>			</p><p class="notes">From: <span><a href="http://biology.plosjournals.org/perlserv/?request=get-document&#38;doi=10.1371/journal.pbio.0040382"  >Interdigitated Paralemniscal and Lemniscal Pathways in the Mouse Barrel Cortex</a></span>Bureau I,&nbsp;von Saint Paul F,&nbsp;Svoboda <span class="citation"><i>PLoS Biology</i> Vol. 4, No. 12, e382 doi:10.1371/journal.pbio.0040382</span>'};
	
	slideshow[13] = {imageUri: 'http://biology.plosjournals.org/archive/1545-7885/4/12/figure/10.1371_journal.pbio.0040382.g006', 
	                 title: 'Figure 14. Somatotopic Maps in VPM and POm',
	                 titlePlain: 'Figure 14. Somatotopic Maps in VPM and POm',
	                 description: '<p>(A) Synaptic input maps (left) for a pair of L5A and L4 cells recorded in the same barrel-related column, and the overlaid input domains (right). Circles indicate the position of the largest responses in the input domains.</p><p>(B) Same as (A) for a pair of L5A and L5B cells.</p><p>(C) Positions of the centers of POm (blue) and VPM (green) input domains for pairs of cells recorded in the same column.</p><p>(D) and (E) Distances of the centers of the input domains from the bottom of VPM (<em>Y</em><sub>POm</sub>, <em>Y</em><sub>VPM</sub>; &#091;D&#093;) and from the POm/VPM boundary (<em>X</em><sub>POm</sub>, <em>X</em><sub>VPM</sub>; &#091;E&#093;) for pairs of cells recorded in the same column (coordinate system is indicated in &#091;C&#093;). Larger symbols indicate overlay of multiple pairs (L5A/L4, <em>n</em> &#061; 13; L5A/L5B, <em>n</em> &#061; 5; L5A/L6A, <em>n</em> &#061; 2). Dashed lines indicate the predicted relationships if VPM and POm somatotopy was mirror symmetric.</p></p><p class="notes">From: <span><a href="http://biology.plosjournals.org/perlserv/?request=get-document&#38;doi=10.1371/journal.pbio.0040382"  >Interdigitated Paralemniscal and Lemniscal Pathways in the Mouse Barrel Cortex</a></span>Bureau I,&nbsp;von Saint Paul F,&nbsp;Svoboda K<span class="citation"><i>PLoS Biology</i> Vol. 4, No. 12, e382 doi:10.1371/journal.pbio.0040382</span>'};
	
	slideshow[14] = {imageUri: 'http://biology.plosjournals.org/archive/1545-7885/4/12/figure/10.1371_journal.pbio.0040382.g007', 
	                 title: 'Figure 15. Laser Scanning Photostimulation Mapping of Intracortical Projections to L2/3 neurons',
	                 titlePlain: 'Figure 15. Laser Scanning Photostimulation Mapping of Intracortical Projections to L2/3 neurons',
	                 description: '<p>(A) Across-barrel slice showing barrels corresponding to rows A&#8211;E (from left to right) under brightfield illumination. In this experiment, the map pattern (red grid) was centered on the septum between the barrels C and D.</p><p>(B) Examples of synaptic input maps for a L2<sup>Barrel</sup> cell (top) and a L3<sup>Barrel</sup> cell (bottom). Black pixels are sites where glutamate uncaging evoked direct responses in the recorded cells, polluting the synaptic responses. Dashed lines indicate the barrel positions. Solid white circles show the cell body positions of the recorded neurons.</p><p>(C) Examples of dendritic morphologies of L2<sup>Barrel</sup> and L3<sup>Barrel</sup> cells (same cells as in &#091;B&#093;).</p></p> <p class="notes">From: <span><a href="http://biology.plosjournals.org/perlserv/?request=get-document&#38;doi=10.1371/journal.pbio.0040382"  >Interdigitated Paralemniscal and Lemniscal Pathways in the Mouse Barrel Cortex</a></span>Bureau I,&nbsp;von Saint Paul F,&nbsp;Svoboda K<span class="citation"><i>PLoS Biology</i> Vol. 4, No. 12, e382 doi:10.1371/journal.pbio.0040382</span>'};
	
	slideshow[15] = {imageUri: 'http://biology.plosjournals.org/archive/1545-7885/4/12/figure/10.1371_journal.pbio.0040382.g008', 
	                 title: 'Figure 16. Interdigitated Intracortical Relays',
	                 titlePlain: 'Figure 16. Interdigitated Intracortical Relays',
	                 description: '<p>(A) Average synaptic input maps for positionally defined L2/3 pyramidal cells.</p><p>(B) Regions of interest used for the analysis in (C&#8211;E).</p><p>(C) The ratio of input from L5A/L4 as a function of the depth of the soma of barrel-related neurons. Dashed black line (top) indicates the pia.</p><p>(D) The ratio of input from L2/3/L4.</p><p>(E) Average synaptic input for projections defined by the presynaptic layer, postsynaptic layer, and postsynaptic column. For L3 neurons in septum and barrels, L4 input is significantly stronger than L5A input; for L2 neurons in barrels, L5A input is significantly stronger than L4 input (<em>p</em> &lt; 0.005, Wilcoxon). Note that this pattern differs from that measured in the rat using essentially identical techniques (see Figure 3e in &#091;13&#093;). L3 input is significantly stronger for L2/3<sup>Septum</sup> cells than for L2/3<sup>Barrel</sup> cells (<em>p</em> &lt; 0.05, Wilcoxon).</p><p>(F) Horizontal profiles of L4 input to L3 cells.</p><p>(G) Horizontal profiles of L5A input to L2 cells.</p> </p> <p class="notes">From: <span><a href="http://biology.plosjournals.org/perlserv/?request=get-document&#38;doi=10.1371/journal.pbio.0040382"  >Interdigitated Paralemniscal and Lemniscal Pathways in the Mouse Barrel Cortex</a></span>Bureau I,&nbsp;von Saint Paul F,&nbsp;Svoboda K<span class="citation"><i>PLoS Biology</i> Vol. 4, No. 12, e382 doi:10.1371/journal.pbio.0040382</span>'};
	
	slideshow[16] = {imageUri: 'http://biology.plosjournals.org/archive/1545-7885/4/12/figure/10.1371_journal.pbio.0040382.g009', 
	                 title: 'Figure 17. Circuit Diagram of the Thalamocortical and Ascending Intracortical Projections in the Barrel Cortex',
	                 titlePlain: 'Figure 17. Circuit Diagram of the Thalamocortical and Ascending Intracortical Projections in the Barrel Cortex',
	                 description: '<p>Lemniscal projections, green; paralemniscal projections, blue. Thick, thin, and dashed lines denote decreasing density of the projection.</p></p><p class="notes">From: <span><a href="http://biology.plosjournals.org/perlserv/?request=get-document&#38;doi=10.1371/journal.pbio.0040382"  >Interdigitated Paralemniscal and Lemniscal Pathways in the Mouse Barrel Cortex</a></span>Bureau I,&nbsp;von Saint Paul F,&nbsp;Svoboda K		<span class="citation"><i>PLoS Biology</i> Vol. 4, No. 12, e382 doi:10.1371/journal.pbio.0040382</span>'};
	
